FIX: fixed all the broken pages.
zoef-yt/gamers-connect pull request #8
Opened 2022-05-21 08:57 UTC by zoef-yt

Fixed all the broken features, and pages and added suggestions from the previous branch.

2022-05-21 09:47 UTC, srishtigautam21 approved these changes
good to merge

2022-05-21 09:55 UTC, dev-prabhat approved these changes
Really like the UI part of this app, Just remove all console.log() from this PR
Else code structure is good

2022-05-21 09:55 UTC, dev-prabhat commented on src/Components/Modal/ModalComponent/CreatePostsCard.jsx
> +	console.log(authUser);
remove console.log

2022-05-21 09:55 UTC, dev-prabhat commented on src/Firebase/FirebaseAuth.js
> +		console.log(isUserInDb);
remove console.log

2022-05-21 09:55 UTC, dev-prabhat commented on src/store/AllUser/AllUserSlice.js
> +			console.log(action.payload);
remove console.log

2022-05-21 12:08 UTC, muskanbagrecha requested changes
Great, abstracted code. Just remove the console.logs.

2022-05-21 12:08 UTC, muskanbagrecha commented on src/Components/Navbar/Navbar.css
> +	transform-style: preserve-3d;
Nice, learnt something new.

2022-05-21 12:08 UTC, muskanbagrecha commented on src/Components/Navbar/Navbar.jsx
> +	const searchedData = search !== '' ? allUsers.filter((user) => user.displayName.toLowerCase().includes(search.toLowerCase())) : allUsers;
In future, you can use debouncing for search.

2022-05-21 12:08 UTC, muskanbagrecha commented on src/Components/SinglePostCard/AllPostComments.jsx
> +				console.log(userComment);
Remove console.log

2022-05-21 12:08 UTC, muskanbagrecha commented on src/Components/SinglePostCard/AllPostComments.jsx
>  	useEffect(() => {
Please add dependency in useeffect

2022-05-21 12:08 UTC, muskanbagrecha commented on src/Components/SinglePostCard/AllPostComments.jsx
> +		console.log(comments);
remove console.log

2022-05-21 12:08 UTC, muskanbagrecha commented on src/Components/SinglePostCard/AllPostComments.jsx
>  	const [triggerEffect, setTriggerEffect] = useState(false);
Need to confirm if it is ideal to use a state only to trigger an effect.

2022-05-21 12:08 UTC, muskanbagrecha commented on src/Components/SinglePostCard/AllPostComments.jsx
> +				allComments.map((comment) => <SingleComment comment={comment.comment} uid={comment.from} timestamp={comment.timestamp} />)
Could destructure here.

2022-05-21 12:08 UTC, muskanbagrecha commented on src/Components/SinglePostCard/SinglePostCard.jsx
>  	const getDelay = (index) => {
Love this logic for animation.

2022-05-21 12:08 UTC, muskanbagrecha commented on src/Firebase/FirebaseAuth.js
> +		console.log(currentUser);
Remove console.log

2022-05-21 12:08 UTC, muskanbagrecha commented on src/Pages/ExplorePage/ExplorePage.jsx
> +			console.log('Inside this');
Remove console.log

2022-05-21 12:08 UTC, muskanbagrecha commented on src/Pages/Home/HomePage.jsx
> +		console.log('allPosts', currentUserHome);
remove console.log

2022-05-21 12:08 UTC, muskanbagrecha commented on src/Pages/Home/HomePage.jsx
> +						console.log(post);
Remove console.log

2022-05-21 12:08 UTC, muskanbagrecha commented on src/Pages/ProfilePage/Components/UserDetails.jsx
> +	console.log(uid);
Remove console.log

2022-05-21 12:08 UTC, muskanbagrecha commented on src/Pages/ProfilePage/Components/UserDetails.jsx
> +		console.log(authUser);
Remove console.log

2022-05-21 15:55 UTC, zoef-yt commented on src/Components/Navbar/Navbar.jsx
> +	const searchedData = search !== '' ? allUsers.filter((user) => user.displayName.toLowerCase().includes(search.toLowerCase())) : allUsers;
Sure will look into it

2022-05-21 15:55 UTC, zoef-yt commented on src/Components/SinglePostCard/AllPostComments.jsx
> +				console.log(userComment);
done

2022-05-21 15:57 UTC, zoef-yt commented on src/Components/SinglePostCard/AllPostComments.jsx
>  	const [triggerEffect, setTriggerEffect] = useState(false);
Okay will confirm this.

2022-05-21 15:57 UTC, zoef-yt commented on src/Components/SinglePostCard/AllPostComments.jsx
> +		console.log(comments);
done

2022-05-21 15:59 UTC, zoef-yt commented on src/Components/SinglePostCard/SinglePostCard.jsx
>  	const getDelay = (index) => {
Thanks

2022-05-21 15:59 UTC, zoef-yt commented on src/Components/SinglePostCard/AllPostComments.jsx
> +				allComments.map((comment) => <SingleComment comment={comment.comment} uid={comment.from} timestamp={comment.timestamp} />)
done

2022-05-21 15:59 UTC, zoef-yt commented on src/Firebase/FirebaseAuth.js
> +		console.log(currentUser);
done

2022-05-21 15:59 UTC, zoef-yt commented on src/Pages/ExplorePage/ExplorePage.jsx
> +			console.log('Inside this');
done

2022-05-21 15:59 UTC, zoef-yt commented on src/Pages/Home/HomePage.jsx
> +		console.log('allPosts', currentUserHome);
done

2022-05-21 15:59 UTC, zoef-yt commented on src/Pages/Home/HomePage.jsx
> +						console.log(post);
done

2022-05-21 15:59 UTC, zoef-yt commented on src/Pages/ProfilePage/Components/UserDetails.jsx
> +	console.log(uid);
done

2022-05-21 16:00 UTC, zoef-yt commented on src/Pages/ProfilePage/Components/UserDetails.jsx
> +		console.log(authUser);
done

2022-05-22 04:51 UTC, zoef-yt commented on src/store/AllUser/AllUserSlice.js
> +			console.log(action.payload);
done

2022-05-22 04:51 UTC, zoef-yt commented on src/Firebase/FirebaseAuth.js
> +		console.log(isUserInDb);
done

2022-05-22 04:51 UTC, zoef-yt commented on src/Components/Modal/ModalComponent/CreatePostsCard.jsx
> +	console.log(authUser);
done

2022-05-22 04:58 UTC, muskanbagrecha approved these changes
Code looks good to merge as you have incorporated the suggested changes. Great work on the project. Right from the UI, animations to the functionality. In future, you can extract logic outside the components. Other than that, everything looks good. Great effort.

2022-05-22 05:03 UTC, merged